create table if not exists public.o8_chain_blocks (
  block_number bigint primary key,
  block_hash text not null unique,
  parent_hash text not null,
  block_timestamp timestamptz not null,
  transaction_count integer not null,
  sampled_gap bigint not null default 0,
  native_transfer_count integer not null default 0,
  native_value_wei numeric(78,0) not null default 0,
  transfer_event_count integer not null default 0,
  contract_call_count integer not null default 0,
  contract_creation_count integer not null default 0,
  failed_transaction_count integer not null default 0,
  admin_call_count integer not null default 0,
  repeated_sender_count integer not null default 0,
  high_value_transfer_count integer not null default 0,
  unique_sender_count integer not null default 0,
  coverage text not null default 'SAMPLED',
  created_at timestamptz not null default now()
);

create table if not exists public.o8_chain_transactions (
  hash text primary key,
  block_number bigint not null references public.o8_chain_blocks(block_number) on delete cascade,
  transaction_index integer not null,
  from_address text not null,
  to_address text,
  value_wei numeric(78,0) not null default 0,
  nonce bigint not null,
  transaction_type integer not null,
  input_selector text,
  input_size integer not null default 0,
  classification text not null,
  status boolean,
  gas_used numeric(78,0),
  effective_gas_price_wei numeric(78,0),
  contract_address text,
  admin_action text,
  created_at timestamptz not null default now()
);

create index if not exists o8_chain_transactions_block_idx on public.o8_chain_transactions(block_number, transaction_index);
create index if not exists o8_chain_transactions_from_idx on public.o8_chain_transactions(from_address, block_number desc);
create index if not exists o8_chain_transactions_to_idx on public.o8_chain_transactions(to_address, block_number desc);

create table if not exists public.o8_chain_events (
  id bigint generated by default as identity primary key,
  transaction_hash text not null references public.o8_chain_transactions(hash) on delete cascade,
  block_number bigint not null references public.o8_chain_blocks(block_number) on delete cascade,
  log_index integer not null,
  contract_address text not null,
  topic0 text,
  topics jsonb not null default '[]'::jsonb,
  data text not null default '0x',
  event_kind text not null default 'unclassified',
  from_address text,
  to_address text,
  amount_or_token_id_raw numeric(78,0),
  created_at timestamptz not null default now(),
  unique(transaction_hash, log_index)
);

create index if not exists o8_chain_events_block_idx on public.o8_chain_events(block_number, log_index);
create index if not exists o8_chain_events_contract_idx on public.o8_chain_events(contract_address, block_number desc);
create index if not exists o8_chain_events_kind_idx on public.o8_chain_events(event_kind, block_number desc);

alter table public.o8_chain_blocks enable row level security;
alter table public.o8_chain_transactions enable row level security;
alter table public.o8_chain_events enable row level security;

drop policy if exists "o8 public read chain blocks" on public.o8_chain_blocks;
create policy "o8 public read chain blocks" on public.o8_chain_blocks for select to anon, authenticated using (true);
drop policy if exists "o8 public read chain transactions" on public.o8_chain_transactions;
create policy "o8 public read chain transactions" on public.o8_chain_transactions for select to anon, authenticated using (true);
drop policy if exists "o8 public read chain events" on public.o8_chain_events;
create policy "o8 public read chain events" on public.o8_chain_events for select to anon, authenticated using (true);

grant select on public.o8_chain_blocks, public.o8_chain_transactions, public.o8_chain_events to anon, authenticated;
grant all on public.o8_chain_blocks, public.o8_chain_transactions, public.o8_chain_events to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.o8_ingest_chain_snapshot(p_snapshot jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  b jsonb := p_snapshot->'block';
  m jsonb := p_snapshot->'metrics';
  current_block bigint := (b->>'blockNumber')::bigint;
  previous_block bigint;
begin
  select max(block_number) into previous_block from public.o8_chain_blocks where block_number < current_block;

  insert into public.o8_chain_blocks(
    block_number, block_hash, parent_hash, block_timestamp, transaction_count, sampled_gap,
    native_transfer_count, native_value_wei, transfer_event_count, contract_call_count,
    contract_creation_count, failed_transaction_count, admin_call_count,
    repeated_sender_count, high_value_transfer_count, unique_sender_count, coverage
  ) values (
    current_block, b->>'blockHash', b->>'parentHash', (b->>'timestamp')::timestamptz,
    (b->>'transactionCount')::integer, greatest(0, current_block - coalesce(previous_block, current_block) - 1),
    (m->>'nativeTransferCount')::integer, (m->>'nativeValueWei')::numeric,
    (m->>'transferEventCount')::integer, (m->>'contractCallCount')::integer,
    (m->>'contractCreationCount')::integer, (m->>'failedTransactionCount')::integer,
    (m->>'adminCallCount')::integer, (m->>'repeatedSenderCount')::integer,
    (m->>'highValueTransferCount')::integer, (m->>'uniqueSenderCount')::integer, 'SAMPLED'
  ) on conflict (block_number) do nothing;

  insert into public.o8_chain_transactions(
    hash, block_number, transaction_index, from_address, to_address, value_wei, nonce,
    transaction_type, input_selector, input_size, classification, status, gas_used,
    effective_gas_price_wei, contract_address, admin_action
  )
  select x.hash, current_block, x.transaction_index, x.from_address, x.to_address, x.value_wei::numeric,
    x.nonce, x.transaction_type, x.input_selector, x.input_size, x.classification, x.status,
    nullif(x.gas_used, '')::numeric, nullif(x.effective_gas_price_wei, '')::numeric,
    x.contract_address, x.admin_action
  from jsonb_to_recordset(coalesce(p_snapshot->'transactions', '[]'::jsonb)) as x(
    hash text, transaction_index integer, from_address text, to_address text, value_wei text,
    nonce bigint, transaction_type integer, input_selector text, input_size integer,
    classification text, status boolean, gas_used text, effective_gas_price_wei text,
    contract_address text, admin_action text
  ) on conflict (hash) do nothing;

  insert into public.o8_chain_events(
    transaction_hash, block_number, log_index, contract_address, topic0, topics, data,
    event_kind, from_address, to_address, amount_or_token_id_raw
  )
  select x.transaction_hash, current_block, x.log_index, x.contract_address, x.topic0,
    x.topics, x.data, x.event_kind, x.from_address, x.to_address,
    nullif(x.amount_or_token_id_raw, '')::numeric
  from jsonb_to_recordset(coalesce(p_snapshot->'events', '[]'::jsonb)) as x(
    transaction_hash text, log_index integer, contract_address text, topic0 text,
    topics jsonb, data text, event_kind text, from_address text, to_address text,
    amount_or_token_id_raw text
  ) on conflict (transaction_hash, log_index) do nothing;

  update public.o8_arms set
    state = 'OBSERVING',
    node_name = 'ROBINHOOD-MAINNET',
    route_confidence = 1,
    last_event_at = now(),
    mood_reason = case id
      when 2 then 'CURRENT is measuring value movement in sampled Robinhood Chain blocks'
      when 5 then 'AUDITOR is inspecting contract creation, failure, and administrative selectors'
      when 6 then 'HUNTER is testing explicit repeated-sender and value-threshold signals'
    end
  where id in (2, 5, 6);

  if (m->>'nativeTransferCount')::integer > 0 or (m->>'transferEventCount')::integer > 0 then
    insert into public.o8_events(type, source, truth, text, metadata) values (
      'flow_sample', 'ARM-02', 'CONNECTED',
      'CURRENT measured sampled block ' || current_block || ': ' || (m->>'nativeTransferCount') ||
        ' native-value transactions and ' || (m->>'transferEventCount') || ' standard Transfer events.',
      jsonb_build_object('blockNumber', current_block, 'coverage', 'SAMPLED', 'nativeTransferCount', (m->>'nativeTransferCount')::integer,
        'nativeValueWei', m->>'nativeValueWei', 'transferEventCount', (m->>'transferEventCount')::integer)
    );
  end if;

  if (m->>'contractCreationCount')::integer > 0 or (m->>'failedTransactionCount')::integer > 0 or (m->>'adminCallCount')::integer > 0 then
    insert into public.o8_events(type, source, truth, text, metadata) values (
      'contract_sample', 'ARM-05', 'CONNECTED',
      'AUDITOR inspected sampled block ' || current_block || ': ' || (m->>'contractCreationCount') ||
        ' creations, ' || (m->>'failedTransactionCount') || ' failed transactions, and ' || (m->>'adminCallCount') || ' known administrative selectors.',
      jsonb_build_object('blockNumber', current_block, 'coverage', 'SAMPLED', 'contractCreationCount', (m->>'contractCreationCount')::integer,
        'failedTransactionCount', (m->>'failedTransactionCount')::integer, 'adminCallCount', (m->>'adminCallCount')::integer)
    );
  end if;

  if (m->>'repeatedSenderCount')::integer > 0 or (m->>'highValueTransferCount')::integer > 0 then
    insert into public.o8_events(type, source, truth, text, metadata) values (
      'anomaly_sample', 'ARM-06', 'CONNECTED',
      'HUNTER flagged sampled block ' || current_block || ': ' || (m->>'repeatedSenderCount') ||
        ' repeated senders and ' || (m->>'highValueTransferCount') || ' transfers at or above the explicit 100 ETH threshold.',
      jsonb_build_object('blockNumber', current_block, 'coverage', 'SAMPLED', 'repeatedSenderCount', (m->>'repeatedSenderCount')::integer,
        'highValueTransferCount', (m->>'highValueTransferCount')::integer, 'thresholdWei', '100000000000000000000')
    );
  end if;

  delete from public.o8_chain_blocks where block_number in (
    select block_number from public.o8_chain_blocks order by block_number desc offset 200
  );

  return jsonb_build_object('blockNumber', current_block, 'transactions', jsonb_array_length(coalesce(p_snapshot->'transactions', '[]'::jsonb)),
    'events', jsonb_array_length(coalesce(p_snapshot->'events', '[]'::jsonb)), 'coverage', 'SAMPLED');
end;
$$;

revoke all on function public.o8_ingest_chain_snapshot(jsonb) from public, anon, authenticated;
grant execute on function public.o8_ingest_chain_snapshot(jsonb) to service_role;
