-- O8 lifecycle enhancement layer.
-- Milestones are emitted only from retained Pons or target-scoped chain evidence.

create table if not exists public.o8_story_milestones (
  id bigint generated by default as identity primary key,
  target_address text not null,
  event_key text not null,
  category text not null,
  event_type text not null,
  title text not null,
  description text not null,
  truth text not null default 'RULE' check (truth in ('CHAIN','RULE')),
  source text not null,
  observed_block bigint,
  evidence jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  unique(target_address, event_key)
);

create table if not exists public.o8_story_state (
  target_address text primary key,
  high_progress numeric(7,3) not null default 0,
  last_high_event_progress numeric(7,3) not null default 0,
  last_progress numeric(7,3),
  last_progress_at timestamptz,
  last_retreat_at timestamptz,
  last_activity_at timestamptz,
  last_activity_block bigint,
  observer_health text not null default 'UNKNOWN',
  silence_state text not null default 'ACTIVE',
  silence_sequence integer not null default 0,
  gap_sequence integer not null default 0,
  graduated_block bigint,
  baseline jsonb,
  baseline_sample_count integer not null default 0,
  baseline_ready_at timestamptz,
  last_deviation_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists o8_story_milestones_recent_idx on public.o8_story_milestones(occurred_at desc);
alter table public.o8_story_milestones enable row level security;
alter table public.o8_story_state enable row level security;
drop policy if exists "o8 public read story milestones" on public.o8_story_milestones;
create policy "o8 public read story milestones" on public.o8_story_milestones for select to anon, authenticated using (true);
drop policy if exists "o8 public read story state" on public.o8_story_state;
create policy "o8 public read story state" on public.o8_story_state for select to anon, authenticated using (true);
grant select on public.o8_story_milestones, public.o8_story_state to anon, authenticated;
grant all on public.o8_story_milestones, public.o8_story_state to service_role;

create or replace function public.o8_emit_story_milestone(
  p_target text,
  p_event_key text,
  p_category text,
  p_event_type text,
  p_title text,
  p_description text,
  p_source text,
  p_observed_block bigint default null,
  p_evidence jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare inserted_id bigint;
begin
  insert into public.o8_story_milestones(
    target_address,event_key,category,event_type,title,description,truth,source,observed_block,evidence
  ) values (
    lower(p_target),p_event_key,p_category,p_event_type,p_title,p_description,'RULE',p_source,p_observed_block,
    coalesce(p_evidence,'{}'::jsonb) || jsonb_build_object('tokenAddress',lower(p_target),'eventKey',p_event_key,'category',p_category)
  ) on conflict(target_address,event_key) do nothing returning id into inserted_id;

  if inserted_id is not null then
    insert into public.o8_events(type,source,truth,text,metadata)
    values(
      p_event_type,p_source,'CONNECTED',p_description,
      coalesce(p_evidence,'{}'::jsonb) || jsonb_build_object(
        'tokenAddress',lower(p_target),'eventKey',p_event_key,'category',p_category,'storyMilestoneId',inserted_id,'coverage','TARGET_SCOPED'
      )
    );
  end if;
  return inserted_id;
end;
$$;

create or replace function public.o8_capture_curve_story()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  target text;
  progress numeric := coalesce(new.graduation_progress,0);
  prior public.o8_story_state%rowtype;
  threshold integer;
  threshold_key text;
  threshold_title text;
  threshold_description text;
  high_band integer;
begin
  select lower(token_address) into target from public.o8_token_targets where id=new.target_id;
  if target is null then return new; end if;

  insert into public.o8_story_state(target_address) values(target) on conflict do nothing;
  select * into prior from public.o8_story_state where target_address=target for update;

  foreach threshold in array array[10,25,50,75,90,95] loop
    if progress >= threshold then
      threshold_key := 'curve_checkpoint_' || threshold;
      threshold_title := 'CURVE ' || threshold || '%';
      threshold_description := case threshold
        when 10 then 'DEPTH verified that the target crossed 10% of the Pons graduation threshold.'
        when 25 then 'DEPTH verified that the target crossed one quarter of the Pons graduation threshold.'
        when 50 then 'DEPTH verified that the target crossed half of the Pons graduation threshold.'
        when 75 then 'DEPTH verified that the target entered ASCENDING above 75% of the Pons graduation threshold.'
        when 90 then 'DEPTH verified that the target crossed 90% of the Pons graduation threshold.'
        else 'DEPTH verified that the target crossed 95% of the Pons graduation threshold. Graduation is close but not yet proven.'
      end;
      perform public.o8_emit_story_milestone(
        target,threshold_key,'CURVE','curve_checkpoint',threshold_title,threshold_description,'ARM-03',new.observed_block,
        jsonb_build_object('graduationProgressPct',progress,'pairedPrincipalWei',new.paired_principal_wei,'graduationThresholdWei',new.graduation_threshold_wei,'snapshotId',new.id)
      );
    end if;
  end loop;

  high_band := floor(progress / 5) * 5;
  if progress > prior.high_progress and high_band >= prior.last_high_event_progress + 5 then
    perform public.o8_emit_story_milestone(
      target,'curve_high_' || high_band,'CURVE','curve_new_high','NEW CURVE HIGH',
      'DEPTH recorded a new retained curve high at ' || round(progress,2) || '%. This is historical progress, not a price signal.',
      'ARM-03',new.observed_block,
      jsonb_build_object('previousHighPct',prior.high_progress,'newHighPct',progress,'pairedPrincipalWei',new.paired_principal_wei,'snapshotId',new.id)
    );
    prior.last_high_event_progress := high_band;
  end if;

  if prior.last_progress is not null and progress <= prior.last_progress - 5
     and (prior.last_retreat_at is null or prior.last_retreat_at < now()-interval '5 minutes') then
    perform public.o8_emit_story_milestone(
      target,'curve_retreat_' || new.id,'CURVE','curve_retreat','CURVE RETREAT',
      'DEPTH measured a curve retreat from ' || round(prior.last_progress,2) || '% to ' || round(progress,2) || '%. The paired principal decreased; no cause or intent is inferred.',
      'ARM-03',new.observed_block,
      jsonb_build_object('previousProgressPct',prior.last_progress,'currentProgressPct',progress,'changePct',progress-prior.last_progress,'snapshotId',new.id)
    );
    prior.last_retreat_at := now();
  end if;

  update public.o8_story_state set
    high_progress=greatest(high_progress,progress),
    last_high_event_progress=greatest(last_high_event_progress,prior.last_high_event_progress),
    last_progress=progress,last_progress_at=new.observed_at,last_retreat_at=prior.last_retreat_at,updated_at=now()
  where target_address=target;
  return new;
end;
$$;

drop trigger if exists o8_capture_curve_story_trigger on public.o8_token_lifecycle_snapshots;
create trigger o8_capture_curve_story_trigger
after insert or update of graduation_progress on public.o8_token_lifecycle_snapshots
for each row execute function public.o8_capture_curve_story();

create or replace function public.o8_capture_curve_sample_from_target()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  target text:=lower(new.token_address);
  old_progress numeric:=old.graduation_progress;
  new_progress numeric:=new.graduation_progress;
  pons_will_snapshot boolean:=false;
  crossed_story_threshold boolean:=false;
  observed bigint:=nullif(new.metadata->>'observedBlock','')::bigint;
begin
  if target is null or new_progress is null then return new; end if;
  insert into public.o8_story_state(target_address,high_progress,last_progress,last_progress_at)
  values(target,new_progress,new_progress,now()) on conflict(target_address) do update
  set high_progress=greatest(public.o8_story_state.high_progress,new_progress),updated_at=now();

  if old_progress is null or old_progress is not distinct from new_progress
     or upper(new.status) not in ('CURVE_ACTIVE','GRADUATED') then return new; end if;

  pons_will_snapshot:=old.status is distinct from new.status
    or (new_progress>old_progress and floor(old_progress/10)<floor(new_progress/10));
  crossed_story_threshold:=
    (old_progress<10 and new_progress>=10) or (old_progress<25 and new_progress>=25)
    or (old_progress<50 and new_progress>=50) or (old_progress<75 and new_progress>=75)
    or (old_progress<90 and new_progress>=90) or (old_progress<95 and new_progress>=95);

  if not pons_will_snapshot and (abs(new_progress-old_progress)>=1 or crossed_story_threshold) then
    insert into public.o8_token_lifecycle_snapshots(
      target_id,status,graduation_progress,paired_principal_wei,graduation_threshold_wei,
      pool_address,observed_block,payload,observed_at
    ) values(
      new.id,new.status,new_progress,new.paired_principal_wei,new.graduation_threshold_wei,
      lower(new.pool_address),observed,
      jsonb_build_object('source','TARGET_PROGRESS_TRIGGER','tokenAddress',target,'progress',new_progress),now()
    );
  end if;
  return new;
end $$;

drop trigger if exists o8_capture_curve_sample_from_target_trigger on public.o8_token_targets;
create trigger o8_capture_curve_sample_from_target_trigger
after update of graduation_progress,status on public.o8_token_targets
for each row execute function public.o8_capture_curve_sample_from_target();

create or replace function public.o8_record_adapting_phase(p_target text,p_block bigint,p_evidence jsonb)
returns void language plpgsql security definer set search_path=public as $$
declare life_id bigint; positions jsonb;
begin
  insert into public.o8_lifecycle_events(target_address,phase_code,phase_name,title,description,truth,observed_block,evidence,occurred_at)
  values(lower(p_target),'06','ADAPTING','A historical behavior baseline became available.',
    'O8 retained 100 post-graduation target blocks and can compare new sampled behavior with that baseline.',
    'RULE',p_block,p_evidence,now())
  on conflict(target_address,phase_code) do nothing returning id into life_id;
  if life_id is null then return; end if;

  insert into public.o8_events(type,source,truth,text,metadata) values(
    'lifecycle_phase','O8-SYSTEM','CONNECTED',
    'PHASE 06 / ADAPTING: O8 retained 100 post-graduation target blocks and can compare new sampled behavior with that baseline.',
    p_evidence || jsonb_build_object('tokenAddress',lower(p_target),'phaseCode','06','phaseName','ADAPTING','lifecycleEventId',life_id)
  );

  positions := jsonb_build_array(
    jsonb_build_object('armId',1,'name','WATCHER','position','The baseline covers retained sampled blocks, not every chain event.','stance','CONFIRM'),
    jsonb_build_object('armId',2,'name','CURRENT','position','Flow deviations are comparisons with sampled history, not price predictions.','stance','COMPARE'),
    jsonb_build_object('armId',3,'name','DEPTH','position','Pool-event deviations do not by themselves establish liquidity quality.','stance','MEASURE'),
    jsonb_build_object('armId',4,'name','CHORUS','position','Sampled participant changes are not complete holder-distribution changes.','stance','WITHHOLD'),
    jsonb_build_object('armId',5,'name','AUDITOR','position','A behavioral baseline is not a contract safety certification.','stance','VERIFY'),
    jsonb_build_object('armId',6,'name','HUNTER','position','Deviation is a rule match; intent and coordination remain unproven.','stance','CHALLENGE'),
    jsonb_build_object('armId',7,'name','KEEPER','position','Pool activity remains distinct from project treasury ownership.','stance','GUARD'),
    jsonb_build_object('armId',8,'name','ARCHIVE','position','The baseline and its limitations are retained together.','stance','PRESERVE')
  );
  insert into public.o8_dissent_records(target_address,phase_code,lifecycle_event_id,truth,summary,positions,evidence,occurred_at)
  values(lower(p_target),'06',life_id,'RULE','Eight rule-layer positions were recorded when the post-graduation baseline became ready.',positions,p_evidence,now())
  on conflict(target_address,phase_code) do nothing;
  insert into public.o8_events(type,source,truth,text,metadata) values(
    'arm_dissent_record','ARM-08','CONNECTED','ARCHIVE preserved eight rule-layer positions for PHASE 06 / ADAPTING without forcing consensus.',
    p_evidence || jsonb_build_object('tokenAddress',lower(p_target),'phaseCode','06','lifecycleEventId',life_id)
  );
end $$;

create or replace function public.o8_capture_target_milestones()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  target text := lower(new.target_address);
  tx_count integer := coalesce((new.metrics->>'transactionCount')::integer,0);
  swap_count integer := coalesce((new.metrics->>'poolSwapCount')::integer,0);
  participant_count integer := coalesce((new.metrics->>'uniqueParticipantCount')::integer,0);
  transfer_count integer := coalesce((new.metrics->>'tokenTransferCount')::integer,0);
  pool_event_count integer := coalesce((new.metrics->>'poolEventCount')::integer,0);
  is_activity boolean;
  state_row public.o8_story_state%rowtype;
  grad_first_block bigint;
  grad_blocks integer;
  avg_tx numeric; avg_swap numeric; avg_participants numeric; avg_transfers numeric;
  v_baseline jsonb;
  deviation_parts text[] := array[]::text[];
  evidence jsonb;
begin
  insert into public.o8_story_state(target_address) values(target) on conflict do nothing;
  select * into state_row from public.o8_story_state where target_address=target for update;
  evidence := jsonb_build_object('blockNumber',new.block_number,'snapshotMetrics',new.metrics,'poolAddress',new.pool_address);
  is_activity := tx_count>0 or transfer_count>0 or pool_event_count>0;

  if tx_count>0 then
    perform public.o8_emit_story_milestone(target,'first_target_transaction','FIRST','first_target_transaction','FIRST TARGET TRANSACTION',
      'WATCHER retained the first target-scoped transaction observed by O8.','ARM-01',new.block_number,evidence);
  end if;
  if swap_count>0 then
    perform public.o8_emit_story_milestone(target,'first_pool_swap','FIRST','first_pool_swap','FIRST POOL SWAP',
      'DEPTH retained the first verified target-pool Swap event observed by O8.','ARM-03',new.block_number,evidence);
  end if;
  if participant_count>0 then
    perform public.o8_emit_story_milestone(target,'first_sampled_participant','FIRST','first_sampled_participant','FIRST SAMPLED PARTICIPANT',
      'CHORUS retained the first non-pool participant address observed in sampled target transfers. This is not a complete holder count.','ARM-04',new.block_number,evidence);
  end if;

  if is_activity then
    if state_row.silence_state='SILENT' then
      perform public.o8_emit_story_milestone(target,'activity_resumed_'||state_row.silence_sequence,'SILENCE','target_activity_resumed','ACTIVITY RESUMED',
        'WATCHER observed target activity after a verified silent interval. Monitoring remained healthy during the distinction.','ARM-01',new.block_number,evidence);
    end if;
    update public.o8_story_state set last_activity_at=new.observed_at,last_activity_block=new.block_number,
      silence_state='ACTIVE',updated_at=now() where target_address=target;
  end if;

  if upper(new.target_status)='GRADUATED' then
    select min(block_number),count(*) into grad_first_block,grad_blocks
    from public.o8_target_block_snapshots where target_address=target and upper(target_status)='GRADUATED';
    update public.o8_story_state set graduated_block=coalesce(graduated_block,grad_first_block),updated_at=now() where target_address=target;

    if swap_count>0 then
      perform public.o8_emit_story_milestone(target,'first_external_pool_swap','POST_GRAD','first_external_pool_swap','FIRST EXTERNAL-POOL SWAP',
        'DEPTH retained the first verified Swap event after the target entered its graduated pool environment.','ARM-03',new.block_number,evidence);
    end if;

    if new.block_number-grad_first_block>=99 then
      perform public.o8_emit_story_milestone(target,'post_grad_100_blocks','POST_GRAD','post_grad_100_blocks','100 POST-GRADUATION BLOCKS',
        'WATCHER verified that the chain advanced 100 blocks beyond the first retained graduated block. This does not mean all 100 blocks contained target activity.','ARM-01',new.block_number,
        evidence || jsonb_build_object('firstGraduatedBlock',grad_first_block,'blockDistance',new.block_number-grad_first_block+1,'sampleCount',grad_blocks));
    end if;

    if grad_blocks>=100 then
      if state_row.baseline_ready_at is null then
        select avg(coalesce((metrics->>'transactionCount')::numeric,0)),
               avg(coalesce((metrics->>'poolSwapCount')::numeric,0)),
               avg(coalesce((metrics->>'uniqueParticipantCount')::numeric,0)),
               avg(coalesce((metrics->>'tokenTransferCount')::numeric,0))
          into avg_tx,avg_swap,avg_participants,avg_transfers
        from (select metrics from public.o8_target_block_snapshots where target_address=target and upper(target_status)='GRADUATED' order by block_number desc limit 100) s;
        v_baseline := jsonb_build_object('sampleCount',100,'avgTransactionCount',round(avg_tx,3),'avgPoolSwapCount',round(avg_swap,3),
          'avgParticipantCount',round(avg_participants,3),'avgTokenTransferCount',round(avg_transfers,3),'throughBlock',new.block_number);
        update public.o8_story_state set baseline=v_baseline,baseline_sample_count=100,baseline_ready_at=now(),updated_at=now() where target_address=target;
        perform public.o8_emit_story_milestone(target,'behavior_baseline_ready','ADAPTATION','behavior_baseline_ready','BEHAVIOR BASELINE READY',
          'ARCHIVE retained a 100-sample post-graduation block baseline. Future deviations are comparisons, not predictions.','ARM-08',new.block_number,v_baseline);
        perform public.o8_record_adapting_phase(target,new.block_number,v_baseline);
        state_row.baseline_ready_at := now(); state_row.baseline := v_baseline;
      end if;
    end if;
  end if;

  if state_row.baseline_ready_at is not null and (state_row.last_deviation_at is null or state_row.last_deviation_at<now()-interval '5 minutes') then
    avg_tx := coalesce((state_row.baseline->>'avgTransactionCount')::numeric,0);
    avg_swap := coalesce((state_row.baseline->>'avgPoolSwapCount')::numeric,0);
    avg_participants := coalesce((state_row.baseline->>'avgParticipantCount')::numeric,0);
    avg_transfers := coalesce((state_row.baseline->>'avgTokenTransferCount')::numeric,0);
    if tx_count>=greatest(3,ceil(avg_tx*3)) then deviation_parts:=array_append(deviation_parts,'transactions'); end if;
    if swap_count>=greatest(2,ceil(avg_swap*3)) then deviation_parts:=array_append(deviation_parts,'pool swaps'); end if;
    if participant_count>=greatest(3,ceil(avg_participants*3)) then deviation_parts:=array_append(deviation_parts,'sampled participants'); end if;
    if transfer_count>=greatest(4,ceil(avg_transfers*3)) then deviation_parts:=array_append(deviation_parts,'token transfers'); end if;
    if array_length(deviation_parts,1)>0 then
      perform public.o8_emit_story_milestone(target,'behavior_deviation_'||new.block_number,'ADAPTATION','behavior_deviation','BEHAVIOR DEVIATION',
        'ARCHIVE detected sampled activity above the retained baseline in: '||array_to_string(deviation_parts,', ')||'. This is a rule match, not an intent or price claim.',
        'ARM-08',new.block_number,evidence || jsonb_build_object('baseline',state_row.baseline,'matchedMetrics',deviation_parts));
      update public.o8_story_state set last_deviation_at=now(),updated_at=now() where target_address=target;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists o8_capture_target_milestones_trigger on public.o8_target_block_snapshots;
create trigger o8_capture_target_milestones_trigger
after insert or update of metrics,target_status,pool_address on public.o8_target_block_snapshots
for each row execute function public.o8_capture_target_milestones();

create or replace function public.o8_capture_post_graduation_pool()
returns trigger language plpgsql security definer set search_path=public as $$
declare target text:=lower(new.token_address); observed bigint;
begin
  if target is null then return new; end if;
  insert into public.o8_story_state(target_address) values(target) on conflict do nothing;
  if coalesce(new.graduated,false) and new.pool_address is not null then
    observed:=nullif(new.metadata->>'observedBlock','')::bigint;
    perform public.o8_emit_story_milestone(target,'graduated_pool_verified','POST_GRAD','graduated_pool_verified','GRADUATED POOL VERIFIED',
      'AUDITOR verified the graduated pool address retained from the Pons and Uniswap V3 route. This is not a liquidity-quality claim.',
      'ARM-05',observed,jsonb_build_object('poolAddress',lower(new.pool_address),'graduationProgressPct',new.graduation_progress,'status',new.status));
  end if;
  return new;
end $$;

drop trigger if exists o8_capture_post_graduation_pool_trigger on public.o8_token_targets;
create trigger o8_capture_post_graduation_pool_trigger
after insert or update of graduated,pool_address,status on public.o8_token_targets
for each row execute function public.o8_capture_post_graduation_pool();

create or replace function public.o8_evaluate_story_state()
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  target_row public.o8_token_targets%rowtype;
  story public.o8_story_state%rowtype;
  observer public.o8_system_bindings%rowtype;
  chain public.o8_sources%rowtype;
  observer_poll timestamptz;
  healthy boolean;
  reference_time timestamptz;
  silent_seconds integer;
begin
  select * into target_row from public.o8_token_targets where id='o8';
  if target_row.token_address is null then return jsonb_build_object('evaluated',false,'reason','no target'); end if;
  insert into public.o8_story_state(target_address) values(lower(target_row.token_address)) on conflict do nothing;
  select * into story from public.o8_story_state where target_address=lower(target_row.token_address) for update;
  select * into observer from public.o8_system_bindings where id='railway-observer';
  select * into chain from public.o8_sources where id='robinhood-mainnet';
  observer_poll:=nullif(observer.details->>'lastPollAt','')::timestamptz;
  healthy:=observer.status='CONNECTED' and observer_poll>now()-interval '45 seconds'
    and chain.status='CONNECTED' and chain.last_checked_at>now()-interval '45 seconds';

  if not healthy then
    if story.observer_health is distinct from 'DEGRADED' then
      story.gap_sequence:=story.gap_sequence+1;
      perform public.o8_emit_story_milestone(lower(target_row.token_address),'observer_gap_'||story.gap_sequence,'INFRA','observer_gap','OBSERVER GAP',
        'WATCHER detected an observation gap. Target silence is not inferred while Railway or chain freshness is degraded.',
        'ARM-01',null,jsonb_build_object('observerStatus',observer.status,'lastPollAt',observer_poll,'chainStatus',chain.status,'chainLastCheckedAt',chain.last_checked_at));
    end if;
    update public.o8_story_state set observer_health='DEGRADED',gap_sequence=story.gap_sequence,updated_at=now() where target_address=lower(target_row.token_address);
    return jsonb_build_object('evaluated',true,'observerHealthy',false,'silenceInferred',false);
  end if;

  if story.observer_health='DEGRADED' then
    perform public.o8_emit_story_milestone(lower(target_row.token_address),'observer_recovered_'||story.gap_sequence,'INFRA','observer_recovered','OBSERVATION RESTORED',
      'WATCHER verified that Railway polling and Robinhood Chain freshness recovered. Silence evaluation may resume.',
      'ARM-01',null,jsonb_build_object('lastPollAt',observer_poll,'chainLastCheckedAt',chain.last_checked_at));
  end if;

  reference_time:=coalesce(story.last_activity_at,story.created_at);
  silent_seconds:=greatest(0,extract(epoch from now()-reference_time)::integer);
  if silent_seconds>=900 and story.silence_state<>'SILENT' then
    story.silence_sequence:=story.silence_sequence+1;
    perform public.o8_emit_story_milestone(lower(target_row.token_address),'silence_15m_'||story.silence_sequence,'SILENCE','target_silence','VERIFIED SILENCE',
      'WATCHER observed no target-scoped transactions, transfers, or pool events for at least 15 minutes while Railway and chain freshness remained healthy.',
      'ARM-01',story.last_activity_block,jsonb_build_object('silenceSeconds',silent_seconds,'lastActivityAt',story.last_activity_at,'observerHealthy',true));
    update public.o8_story_state set observer_health='HEALTHY',silence_state='SILENT',silence_sequence=story.silence_sequence,updated_at=now()
      where target_address=lower(target_row.token_address);
  else
    update public.o8_story_state set observer_health='HEALTHY',updated_at=now() where target_address=lower(target_row.token_address);
  end if;
  return jsonb_build_object('evaluated',true,'observerHealthy',true,'silenceState',case when silent_seconds>=900 then 'SILENT' else story.silence_state end,'silenceSeconds',silent_seconds);
end $$;

create or replace function public.o8_tick()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  specimen public.o8_specimen%rowtype;
  next_tick bigint;
  story_result jsonb;
begin
  story_result:=public.o8_evaluate_story_state();
  select * into specimen from public.o8_specimen where id='o8' for update;
  if specimen.updated_at>now()-interval '12 seconds' then
    return jsonb_build_object('advanced',false,'heartbeat',specimen.tick_count,'story',story_result);
  end if;
  next_tick:=specimen.tick_count+1;
  update public.o8_specimen set
    tick_count=next_tick,
    next_scan_at=case when next_scan_at<=now() then now()+interval '60 seconds' else next_scan_at end,
    next_sync_at=now()+interval '5 minutes',
    updated_at=now()
  where id='o8';
  return jsonb_build_object('advanced',true,'heartbeat',next_tick,'story',story_result);
end $$;

revoke all on function public.o8_emit_story_milestone(text,text,text,text,text,text,text,bigint,jsonb) from public,anon,authenticated;
revoke all on function public.o8_evaluate_story_state() from public,anon,authenticated;
grant execute on function public.o8_emit_story_milestone(text,text,text,text,text,text,text,bigint,jsonb) to service_role;
grant execute on function public.o8_evaluate_story_state() to service_role;

-- The old snapshot-count adaptation trigger is replaced by an explicit 100 post-graduation block baseline.
drop trigger if exists o8_capture_adaptation_story_trigger on public.o8_target_block_snapshots;

-- Clean new story records when a test target is replaced or cleared.
create or replace function public.o8_cleanup_story_target()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if old.token_address is not null and lower(old.token_address) is distinct from lower(new.token_address) then
    delete from public.o8_story_milestones where target_address=lower(old.token_address);
    delete from public.o8_story_state where target_address=lower(old.token_address);
  end if;
  return new;
end $$;
drop trigger if exists o8_cleanup_story_target_trigger on public.o8_token_targets;
create trigger o8_cleanup_story_target_trigger after update of token_address on public.o8_token_targets
for each row execute function public.o8_cleanup_story_target();

do $$ begin
  begin alter publication supabase_realtime add table public.o8_story_milestones; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.o8_story_state; exception when duplicate_object then null; end;
end $$;

-- Backfill the currently registered target from retained evidence.
insert into public.o8_story_state(target_address)
select lower(token_address) from public.o8_token_targets where id='o8' and token_address is not null
on conflict do nothing;

update public.o8_token_lifecycle_snapshots s set graduation_progress=s.graduation_progress
where s.id=(select id from public.o8_token_lifecycle_snapshots where target_id='o8' order by graduation_progress desc nulls last,id desc limit 1);

update public.o8_target_block_snapshots s set metrics=s.metrics
where (s.target_address,s.block_number) in (
  select target_address,min(block_number) from public.o8_target_block_snapshots
  where coalesce((metrics->>'transactionCount')::integer,0)>0 group by target_address
  union
  select target_address,min(block_number) from public.o8_target_block_snapshots
  where coalesce((metrics->>'poolSwapCount')::integer,0)>0 group by target_address
  union
  select target_address,min(block_number) from public.o8_target_block_snapshots
  where coalesce((metrics->>'uniqueParticipantCount')::integer,0)>0 group by target_address
  union
  select target_address,max(block_number) from public.o8_target_block_snapshots
  where coalesce((metrics->>'transactionCount')::integer,0)>0
     or coalesce((metrics->>'tokenTransferCount')::integer,0)>0
     or coalesce((metrics->>'poolEventCount')::integer,0)>0 group by target_address
);

update public.o8_token_targets set status=status where id='o8' and token_address is not null;
