create table if not exists public.o8_token_targets (
  id text primary key,
  platform text not null default 'PONS',
  symbol text not null default 'O8',
  token_name text,
  token_address text unique,
  status text not null default 'AWAITING_LAUNCH',
  factory_address text not null,
  locker_address text,
  deployer_address text,
  pool_address text,
  pair_token_address text,
  launch_tx_hash text,
  launch_block bigint,
  launched_at timestamptz,
  initial_buy_wei numeric(78,0),
  total_supply numeric(78,0),
  dex_id bigint,
  launch_config_id bigint,
  position_id numeric(78,0),
  restrictions_end_block bigint,
  pool_fee integer,
  graduation_progress numeric(7,3),
  paired_principal_wei numeric(78,0),
  graduation_threshold_wei numeric(78,0),
  graduated boolean not null default false,
  price_usd numeric,
  market_cap_usd numeric,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.o8_token_lifecycle_snapshots (
  id bigint generated by default as identity primary key,
  target_id text not null references public.o8_token_targets(id) on delete cascade,
  observed_at timestamptz not null default now(),
  status text not null,
  graduation_progress numeric(7,3),
  paired_principal_wei numeric(78,0),
  graduation_threshold_wei numeric(78,0),
  pool_address text,
  pool_liquidity numeric(78,0),
  pool_sqrt_price_x96 numeric(78,0),
  observed_block bigint,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists o8_token_lifecycle_target_idx
  on public.o8_token_lifecycle_snapshots(target_id, observed_at desc);

alter table public.o8_token_targets enable row level security;
alter table public.o8_token_lifecycle_snapshots enable row level security;

drop policy if exists "o8 public read token targets" on public.o8_token_targets;
create policy "o8 public read token targets" on public.o8_token_targets
  for select to anon, authenticated using (true);
drop policy if exists "o8 public read token lifecycle" on public.o8_token_lifecycle_snapshots;
create policy "o8 public read token lifecycle" on public.o8_token_lifecycle_snapshots
  for select to anon, authenticated using (true);

grant select on public.o8_token_targets, public.o8_token_lifecycle_snapshots to anon, authenticated;
grant all on public.o8_token_targets, public.o8_token_lifecycle_snapshots to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.o8_token_targets(id, platform, symbol, status, factory_address, locker_address, pair_token_address, total_supply, launch_config_id, dex_id, pool_fee, graduation_threshold_wei, metadata)
values (
  'o8', 'PONS', 'O8', 'AWAITING_LAUNCH',
  '0xA5aAb3F0c6EeadF30Ef1D3Eb997108E976351feB',
  '0x736D76699C26D0d966744cAe304C000d471f7F35',
  '0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73',
  1000000000000000000000000000, 0, 0, 10000, 4200000000000000000,
  '{"launchpadUrl":"https://www.ponsfamily.com/launchpad","coverage":"FACTORY_VERIFIED"}'::jsonb
)
on conflict (id) do update set
  platform = excluded.platform,
  factory_address = excluded.factory_address,
  locker_address = excluded.locker_address,
  pair_token_address = excluded.pair_token_address,
  launch_config_id = excluded.launch_config_id,
  dex_id = excluded.dex_id,
  pool_fee = excluded.pool_fee,
  graduation_threshold_wei = excluded.graduation_threshold_wei,
  metadata = public.o8_token_targets.metadata || excluded.metadata;

insert into public.o8_sources(id, label, kind, truth, status, payload)
values (
  'pons-launchpad', 'Pons Launchpad lifecycle', 'launchpad-lifecycle', 'CONNECTED', 'CONNECTING',
  '{"factory":"0xA5aAb3F0c6EeadF30Ef1D3Eb997108E976351feB","network":"Robinhood Chain Mainnet"}'::jsonb
)
on conflict (id) do update set label = excluded.label, kind = excluded.kind, truth = excluded.truth;

insert into public.o8_system_bindings(id, label, status, details)
values (
  'pons-launchpad', 'Pons Launchpad', 'CONNECTING',
  '{"factory":"0xA5aAb3F0c6EeadF30Ef1D3Eb997108E976351feB","tokenRegistration":"AWAITING"}'::jsonb
)
on conflict (id) do update set label = excluded.label;

update public.o8_system_bindings
set status = 'AWAITING_LAUNCH',
    details = jsonb_build_object(
      'symbol', 'O8',
      'contractAddress', null,
      'launchpad', 'PONS',
      'factory', '0xA5aAb3F0c6EeadF30Ef1D3Eb997108E976351feB'
    ),
    updated_at = now()
where id = 'o8-token' and coalesce(details->>'contractAddress', '') = '';

create or replace function public.o8_register_pons_token(p_token_address text, p_launch_tx_hash text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_token_address !~* '^0x[0-9a-f]{40}$' then
    raise exception 'invalid token address';
  end if;
  if p_launch_tx_hash is not null and p_launch_tx_hash !~* '^0x[0-9a-f]{64}$' then
    raise exception 'invalid launch transaction hash';
  end if;

  update public.o8_token_targets
  set token_address = lower(p_token_address),
      launch_tx_hash = coalesce(lower(p_launch_tx_hash), launch_tx_hash),
      status = 'VERIFYING',
      updated_at = now()
  where id = 'o8';

  update public.o8_system_bindings
  set status = 'VERIFYING',
      details = details || jsonb_build_object('contractAddress', lower(p_token_address), 'launchpad', 'PONS'),
      updated_at = now()
  where id = 'o8-token';

  return jsonb_build_object('registered', true, 'tokenAddress', lower(p_token_address), 'status', 'VERIFYING');
end;
$$;

create or replace function public.o8_ingest_pons_launchpad(p_snapshot jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  platform jsonb := p_snapshot->'platform';
  target jsonb := p_snapshot->'target';
  previous_status text;
  previous_progress numeric;
  previous_binding_status text;
  next_status text := coalesce(target->>'status', 'AWAITING_LAUNCH');
  next_progress numeric := nullif(target->>'graduationProgressPct', '')::numeric;
  event_id bigint;
begin
  select status, graduation_progress into previous_status, previous_progress
  from public.o8_token_targets where id = 'o8' for update;
  select status into previous_binding_status from public.o8_system_bindings where id = 'pons-launchpad';

  update public.o8_sources
  set status = 'CONNECTED',
      latency_ms = nullif(platform->>'latencyMs', '')::integer,
      last_checked_at = now(),
      payload = platform
  where id = 'pons-launchpad';

  update public.o8_system_bindings
  set status = 'CONNECTED',
      details = platform,
      updated_at = now()
  where id = 'pons-launchpad';

  if previous_binding_status is distinct from 'CONNECTED' then
    insert into public.o8_events(type, source, truth, text, metadata)
    values (
      'launchpad_bound', 'O8-SYSTEM', 'CONNECTED',
      'Pons Launchpad lifecycle is bound: factory, locker, Uniswap V3 route, launch configuration, and graduation threshold were verified on Robinhood Chain.',
      jsonb_build_object('factory', platform->>'factory', 'locker', platform->>'locker', 'graduationThresholdWei', platform->>'graduationThresholdWei')
    ) returning id into event_id;
  end if;

  if target is null or coalesce(target->>'tokenAddress', '') = '' then
    update public.o8_token_targets
    set status = 'AWAITING_LAUNCH', updated_at = now()
    where id = 'o8' and token_address is null;

    update public.o8_system_bindings
    set status = 'AWAITING_LAUNCH',
        details = jsonb_build_object(
          'symbol', 'O8', 'contractAddress', null, 'launchpad', 'PONS',
          'factory', platform->>'factory', 'stage', 'AWAITING_LAUNCH'
        ),
        updated_at = now()
    where id = 'o8-token';

    return jsonb_build_object('status', 'AWAITING_LAUNCH', 'eventId', event_id);
  end if;

  update public.o8_token_targets set
    token_name = target->>'name',
    symbol = coalesce(nullif(target->>'symbol', ''), symbol),
    token_address = lower(target->>'tokenAddress'),
    status = next_status,
    deployer_address = lower(target->>'deployer'),
    pool_address = lower(target->>'pool'),
    pair_token_address = lower(target->>'pairToken'),
    launch_tx_hash = coalesce(lower(target->>'launchTxHash'), launch_tx_hash),
    launch_block = nullif(target->>'launchBlock', '')::bigint,
    launched_at = nullif(target->>'launchedAt', '')::timestamptz,
    initial_buy_wei = nullif(target->>'initialBuyWei', '')::numeric,
    total_supply = nullif(target->>'totalSupply', '')::numeric,
    dex_id = nullif(target->>'dexId', '')::bigint,
    launch_config_id = nullif(target->>'launchConfigId', '')::bigint,
    position_id = nullif(target->>'positionId', '')::numeric,
    restrictions_end_block = nullif(target->>'restrictionsEndBlock', '')::bigint,
    pool_fee = nullif(target->>'poolFee', '')::integer,
    graduation_progress = next_progress,
    paired_principal_wei = nullif(target->>'pairedPrincipalWei', '')::numeric,
    graduation_threshold_wei = nullif(target->>'graduationThresholdWei', '')::numeric,
    graduated = coalesce((target->>'graduated')::boolean, false),
    price_usd = nullif(target->>'priceUsd', '')::numeric,
    market_cap_usd = nullif(target->>'marketCapUsd', '')::numeric,
    metadata = coalesce(target->'metadata', '{}'::jsonb),
    updated_at = now()
  where id = 'o8';

  update public.o8_system_bindings
  set status = next_status,
      details = jsonb_build_object(
        'symbol', coalesce(target->>'symbol', 'O8'),
        'contractAddress', lower(target->>'tokenAddress'),
        'launchpad', 'PONS',
        'factory', platform->>'factory',
        'poolAddress', lower(target->>'pool'),
        'stage', next_status,
        'graduated', coalesce((target->>'graduated')::boolean, false),
        'graduationProgressPct', next_progress
      ),
      updated_at = now()
  where id = 'o8-token';

  if previous_status is distinct from next_status
     or floor(coalesce(previous_progress, -1) / 10) < floor(coalesce(next_progress, -1) / 10) then
    insert into public.o8_token_lifecycle_snapshots(
      target_id, status, graduation_progress, paired_principal_wei, graduation_threshold_wei,
      pool_address, pool_liquidity, pool_sqrt_price_x96, observed_block, payload
    ) values (
      'o8', next_status, next_progress,
      nullif(target->>'pairedPrincipalWei', '')::numeric,
      nullif(target->>'graduationThresholdWei', '')::numeric,
      lower(target->>'pool'), nullif(target->>'poolLiquidity', '')::numeric,
      nullif(target->>'poolSqrtPriceX96', '')::numeric,
      nullif(target->>'observedBlock', '')::bigint, target
    );
  end if;

  if previous_status in ('AWAITING_LAUNCH', 'VERIFYING') and next_status in ('CURVE_ACTIVE', 'GRADUATED') then
    insert into public.o8_events(type, source, truth, text, metadata)
    values (
      'token_launched', 'O8-SYSTEM', 'CONNECTED',
      '$O8 was verified as a Pons launch on Robinhood Chain. The token, deployer, pool, pair asset, launch transaction, and curve state are retained.',
      jsonb_build_object('tokenAddress', lower(target->>'tokenAddress'), 'poolAddress', lower(target->>'pool'), 'launchTxHash', lower(target->>'launchTxHash'), 'status', next_status)
    ) returning id into event_id;
  elsif previous_status is distinct from 'GRADUATED' and next_status = 'GRADUATED' then
    insert into public.o8_events(type, source, truth, text, metadata)
    values (
      'token_graduated', 'ARM-03', 'CONNECTED',
      'DEPTH verified that $O8 reached the Pons graduation threshold. Post-graduation Uniswap V3 pool monitoring is active.',
      jsonb_build_object('tokenAddress', lower(target->>'tokenAddress'), 'poolAddress', lower(target->>'pool'), 'graduationProgressPct', 100)
    ) returning id into event_id;
  elsif floor(coalesce(previous_progress, -1) / 10) < floor(coalesce(next_progress, -1) / 10) then
    insert into public.o8_events(type, source, truth, text, metadata)
    values (
      'graduation_progress', 'ARM-03', 'CONNECTED',
      'DEPTH measured Pons graduation progress at ' || round(next_progress, 1) || '%. This is an on-chain curve state, not a price prediction.',
      jsonb_build_object('tokenAddress', lower(target->>'tokenAddress'), 'graduationProgressPct', next_progress, 'pairedPrincipalWei', target->>'pairedPrincipalWei', 'thresholdWei', target->>'graduationThresholdWei')
    ) returning id into event_id;
  end if;

  update public.o8_arms
  set state = 'OBSERVING',
      node_name = 'PONS-' || case when next_status = 'GRADUATED' then 'V3-POOL' else 'CURVE' end,
      route_confidence = 1,
      mood = case when next_status = 'GRADUATED' then 'focused' else 'guarded' end,
      mood_reason = 'DEPTH is measuring verified Pons pool and graduation state for $O8',
      last_event_at = now()
  where id = 3;

  return jsonb_build_object('status', next_status, 'progress', next_progress, 'eventId', event_id, 'tokenAddress', lower(target->>'tokenAddress'));
end;
$$;

revoke all on function public.o8_register_pons_token(text, text) from public, anon, authenticated;
revoke all on function public.o8_ingest_pons_launchpad(jsonb) from public, anon, authenticated;
grant execute on function public.o8_register_pons_token(text, text) to service_role;
grant execute on function public.o8_ingest_pons_launchpad(jsonb) to service_role;
