-- O8 narrative lifecycle, rule-layer arm divergence, and verified graduation ceremony.
-- Every persisted record is derived from a real target state transition.

create table if not exists public.o8_lifecycle_events (
  id bigint generated by default as identity primary key,
  target_address text not null,
  phase_code text not null,
  phase_name text not null,
  title text not null,
  description text not null,
  truth text not null default 'RULE' check (truth in ('CHAIN', 'RULE')),
  observed_block bigint,
  evidence jsonb not null default '{}'::jsonb,
  ceremony jsonb,
  occurred_at timestamptz not null default now(),
  unique (target_address, phase_code)
);

create table if not exists public.o8_dissent_records (
  id bigint generated by default as identity primary key,
  target_address text not null,
  phase_code text not null,
  lifecycle_event_id bigint references public.o8_lifecycle_events(id) on delete cascade,
  truth text not null default 'RULE' check (truth = 'RULE'),
  summary text not null,
  positions jsonb not null,
  evidence jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  unique (target_address, phase_code)
);

create index if not exists o8_lifecycle_events_recent_idx on public.o8_lifecycle_events(occurred_at desc);
create index if not exists o8_dissent_records_recent_idx on public.o8_dissent_records(occurred_at desc);

alter table public.o8_lifecycle_events enable row level security;
alter table public.o8_dissent_records enable row level security;
drop policy if exists "o8 public read lifecycle events" on public.o8_lifecycle_events;
create policy "o8 public read lifecycle events" on public.o8_lifecycle_events for select to anon, authenticated using (true);
drop policy if exists "o8 public read dissent records" on public.o8_dissent_records;
create policy "o8 public read dissent records" on public.o8_dissent_records for select to anon, authenticated using (true);
grant select on public.o8_lifecycle_events, public.o8_dissent_records to anon, authenticated;
grant all on public.o8_lifecycle_events, public.o8_dissent_records to service_role;

create or replace function public.o8_capture_target_story()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target text := lower(new.token_address);
  rank integer := 0;
  idx integer;
  inserted_id bigint;
  v_phase_code text;
  v_phase_name text;
  phase_title text;
  phase_description text;
  phase_evidence jsonb;
  phase_ceremony jsonb;
  positions jsonb;
  observed_block bigint := coalesce(new.launch_block, nullif(new.metadata->>'observedBlock', '')::bigint);
begin
  if tg_op = 'UPDATE' and old.token_address is not null
     and lower(old.token_address) is distinct from lower(new.token_address) then
    delete from public.o8_dissent_records where target_address = lower(old.token_address);
    delete from public.o8_lifecycle_events where target_address = lower(old.token_address);
  end if;

  if target is null or target = '' then return new; end if;

  rank := case
    when upper(new.status) = 'ARCHIVED' then 7
    when upper(new.status) = 'ADAPTING' then 6
    when coalesce(new.graduated, false) or upper(new.status) = 'GRADUATED' then 5
    when coalesce(new.graduation_progress, 0) >= 75 then 4
    when upper(new.status) in ('CURVE_ACTIVE', 'LIVE', 'FEEDING') then 3
    when new.deployer_address is not null then 2
    else 1
  end;

  for idx in 1..rank loop
    v_phase_code := lpad(idx::text, 2, '0');
    v_phase_name := (array['AWAKENED','ATTACHED','FEEDING','ASCENDING','GRADUATED','ADAPTING','ARCHIVED'])[idx];
    phase_title := case idx
      when 1 then 'A target signal entered the organism.'
      when 2 then 'Eight arms attached to one verified contract.'
      when 3 then 'The organism began ingesting target-scoped evidence.'
      when 4 then 'The target entered the final quarter of the Pons curve.'
      when 5 then 'The graduation threshold was verified on-chain.'
      when 6 then 'A historical behavior baseline became available.'
      else 'Live observation ended; the record remains.'
    end;
    phase_description := case idx
      when 1 then 'The submitted contract address is being checked against the Pons factory before target claims are allowed.'
      when 2 then 'Pons origin, deployer, pair asset and pool route were retained for the registered target.'
      when 3 then 'O8 began retaining transactions, transfers, participants, contract calls and pool evidence scoped to the target.'
      when 4 then 'Verified curve progress crossed 75%. This is a lifecycle threshold, not a price prediction.'
      when 5 then 'Pons reported graduation and the verified pool route became the target environment.'
      when 6 then 'New target activity can now be compared with retained post-graduation observations.'
      else 'The target is no longer observed live. Its verified lifecycle remains preserved.'
    end;
    phase_evidence := jsonb_strip_nulls(jsonb_build_object(
      'tokenAddress', target,
      'status', new.status,
      'deployerAddress', lower(new.deployer_address),
      'poolAddress', lower(new.pool_address),
      'launchTxHash', lower(new.launch_tx_hash),
      'launchBlock', new.launch_block,
      'observedBlock', observed_block,
      'graduationProgressPct', new.graduation_progress,
      'pairedPrincipalWei', new.paired_principal_wei,
      'graduationThresholdWei', new.graduation_threshold_wei
    ));
    phase_ceremony := case when idx = 5 then jsonb_strip_nulls(jsonb_build_object(
      'verified', true,
      'tokenAddress', target,
      'poolAddress', lower(new.pool_address),
      'launchTxHash', lower(new.launch_tx_hash),
      'observedBlock', observed_block,
      'graduationProgressPct', new.graduation_progress,
      'graduationThresholdWei', new.graduation_threshold_wei,
      'declaration', 'THE TARGET CROSSED THE VERIFIED PONS GRADUATION THRESHOLD.'
    )) else null end;

    inserted_id := null;
    insert into public.o8_lifecycle_events(
      target_address, phase_code, phase_name, title, description, truth,
      observed_block, evidence, ceremony, occurred_at
    ) values (
      target, v_phase_code, v_phase_name, phase_title, phase_description, 'RULE',
      observed_block, phase_evidence, phase_ceremony, now()
    ) on conflict (target_address, phase_code) do nothing
    returning id into inserted_id;

    if inserted_id is not null then
      insert into public.o8_events(type, source, truth, text, metadata)
      values (
        case when idx = 5 then 'graduation_ceremony' else 'lifecycle_phase' end,
        case when idx = 5 then 'O8-COUNCIL' else 'O8-SYSTEM' end,
        'CONNECTED',
        'PHASE ' || v_phase_code || ' / ' || v_phase_name || ': ' || phase_description,
        phase_evidence || jsonb_build_object('phaseCode', v_phase_code, 'phaseName', v_phase_name, 'lifecycleEventId', inserted_id)
      );

      if idx in (2, 4, 5, 6) then
        positions := jsonb_build_array(
          jsonb_build_object('armId',1,'name','WATCHER','position','The transition is recorded only because the target state changed in retained evidence.','stance','CONFIRM'),
          jsonb_build_object('armId',2,'name','CURRENT','position',case when idx=5 then 'Graduation changes the market route; it does not prove continuing inflow or momentum.' else 'A lifecycle transition alone does not establish directional capital flow.' end,'stance','RESERVE'),
          jsonb_build_object('armId',3,'name','DEPTH','position',case when idx=5 then 'The Pons threshold is satisfied and the verified pool becomes the liquidity environment.' when idx=4 then 'The curve crossed 75%, but the remaining distance and liquidity conditions still matter.' else 'Liquidity claims remain limited to verified curve and pool state.' end,'stance','MEASURE'),
          jsonb_build_object('armId',4,'name','CHORUS','position','A phase change does not establish holder distribution, community size, or participant intent.','stance','WITHHOLD'),
          jsonb_build_object('armId',5,'name','AUDITOR','position','Contract origin and recorded addresses may be verified; lifecycle status is not a safety certification.','stance','VERIFY'),
          jsonb_build_object('armId',6,'name','HUNTER','position','No bot, coordination, or malicious-intent conclusion follows from this transition alone.','stance','CHALLENGE'),
          jsonb_build_object('armId',7,'name','KEEPER','position','Paired principal and pool activity are not automatically project treasury balances.','stance','GUARD'),
          jsonb_build_object('armId',8,'name','ARCHIVE','position','The conflicting limits and confirmations are preserved without forcing consensus.','stance','PRESERVE')
        );
        insert into public.o8_dissent_records(
          target_address, phase_code, lifecycle_event_id, truth, summary, positions, evidence, occurred_at
        ) values (
          target, v_phase_code, inserted_id, 'RULE',
          'Eight deterministic arm positions were recorded for phase ' || v_phase_code || '. They are rule-layer perspectives, not eight simultaneous LLM calls.',
          positions, phase_evidence, now()
        ) on conflict (target_address, phase_code) do nothing;

        insert into public.o8_events(type, source, truth, text, metadata)
        values (
          'arm_dissent_record', 'ARM-08', 'CONNECTED',
          'ARCHIVE preserved eight rule-layer positions for PHASE ' || v_phase_code || ' / ' || v_phase_name || ' without forcing consensus.',
          phase_evidence || jsonb_build_object('phaseCode', v_phase_code, 'phaseName', v_phase_name, 'lifecycleEventId', inserted_id)
        );
      end if;
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists o8_capture_target_story_trigger on public.o8_token_targets;
create trigger o8_capture_target_story_trigger
after insert or update of token_address, status, deployer_address, pool_address, graduation_progress, graduated
on public.o8_token_targets
for each row execute function public.o8_capture_target_story();

create or replace function public.o8_capture_adaptation_story()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  snapshot_count integer;
begin
  if upper(new.target_status) <> 'GRADUATED' then return new; end if;
  if exists (select 1 from public.o8_lifecycle_events where target_address = lower(new.target_address) and phase_code = '06') then return new; end if;
  select count(*) into snapshot_count from public.o8_target_block_snapshots where target_address = lower(new.target_address);
  if snapshot_count >= 100 then
    update public.o8_token_targets
    set status = 'ADAPTING', updated_at = now()
    where id = 'o8' and lower(token_address) = lower(new.target_address) and status = 'GRADUATED';
  end if;
  return new;
end;
$$;

drop trigger if exists o8_capture_adaptation_story_trigger on public.o8_target_block_snapshots;
create trigger o8_capture_adaptation_story_trigger
after insert on public.o8_target_block_snapshots
for each row execute function public.o8_capture_adaptation_story();

do $$
begin
  begin alter publication supabase_realtime add table public.o8_lifecycle_events; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.o8_dissent_records; exception when duplicate_object then null; end;
end $$;

-- Backfill the current target only if one is already registered.
update public.o8_token_targets set status = status where id = 'o8' and token_address is not null;

