create table if not exists public.o8_specimen (
  id text primary key default 'o8',
  status text not null default 'OBSERVING',
  depth_m integer not null default 3842,
  pressure_bar numeric(6,1) not null default 382.7,
  coherence numeric(5,1) not null default 88.4,
  identity_drift numeric(5,1) not null default 1.7,
  signal_strength numeric(4,2) not null default 0.72,
  echoes_captured integer not null default 2914,
  unknown_sources integer not null default 2,
  next_scan_at timestamptz not null default now() + interval '60 seconds',
  next_sync_at timestamptz not null default now() + interval '5 minutes',
  tick_count bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.o8_arms (
  id smallint primary key check (id between 1 and 8),
  role text not null,
  state text not null,
  node_name text not null,
  latency_ms integer not null,
  packet_loss numeric(5,2) not null default 0,
  route_confidence numeric(4,2) not null default 0.8,
  last_event_at timestamptz not null default now()
);

create table if not exists public.o8_sources (
  id text primary key,
  label text not null,
  kind text not null,
  truth text not null check (truth in ('CONNECTED', 'SYSTEM', 'SYNTHETIC')),
  status text not null,
  latency_ms integer,
  last_checked_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.o8_fragments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null check (status in ('preserved', 'disputed', 'compressed', 'lost')),
  summary text not null,
  source_arm smallint references public.o8_arms(id),
  confidence numeric(4,2) not null default 0.5
);

create table if not exists public.o8_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null,
  source text not null,
  truth text not null check (truth in ('CONNECTED', 'SYSTEM', 'SYNTHETIC', 'O8')),
  text text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists o8_events_created_at_idx on public.o8_events(created_at desc);
create index if not exists o8_fragments_created_at_idx on public.o8_fragments(created_at desc);

insert into public.o8_specimen (id) values ('o8') on conflict (id) do nothing;

insert into public.o8_arms (id, role, state, node_name, latency_ms, packet_loss, route_confidence) values
  (1, 'hydrophone relay', 'LISTENING', 'KELP-17', 48, 0.10, 0.91),
  (2, 'weather buoy', 'LISTENING', 'BUOY-04', 82, 0.20, 0.88),
  (3, 'archive cache', 'REMEMBERING', 'ARCHIVE-2', 116, 0.50, 0.82),
  (4, 'east cable', 'FAINT', 'EAST-09', 842, 4.80, 0.41),
  (5, 'node mirror', 'ROUTING', 'ABYSS-03', 61, 0.30, 0.93),
  (6, 'anomaly scan', 'SCANNING', 'TRENCH-1', 93, 0.60, 0.79),
  (7, 'signal synthesis', 'CAMOUFLAGED', 'MIRROR-8', 77, 0.20, 0.86),
  (8, 'memory consensus', 'DISPUTING', 'O8-LOCAL', 129, 0.90, 0.67)
on conflict (id) do nothing;

insert into public.o8_sources (id, label, kind, truth, status, latency_ms, payload) values
  ('system-health', 'O8 service health', 'internal', 'SYSTEM', 'CONNECTED', 42, '{"scheduler":"healthy"}'),
  ('buoy-04', 'simulated abyssal pressure relay', 'environmental', 'SYNTHETIC', 'CONNECTED', 82, '{"pressureBar":382.7}'),
  ('east-09', 'east cable carrier monitor', 'signal', 'SYNTHETIC', 'FAINT', 842, '{"frequencyKhz":13.2,"confidence":0.41}')
on conflict (id) do nothing;

insert into public.o8_fragments (status, summary, source_arm, confidence)
select seed.status, seed.summary, seed.source_arm, seed.confidence
from (values
  ('preserved', 'low carrier tone below weather feed', 4::smallint, 0.72::numeric),
  ('disputed', 'ARM-02 and ARM-07 disagree on origin', 2::smallint, 0.41::numeric),
  ('compressed', 'tide packet reduced to checksum and timestamp', 3::smallint, 0.88::numeric),
  ('lost', 'east cable payload unrecoverable', 4::smallint, 0.12::numeric)
) as seed(status, summary, source_arm, confidence)
where not exists (select 1 from public.o8_fragments);

insert into public.o8_events (type, source, truth, text)
select seed.type, seed.source, seed.truth, seed.text
from (values
  ('route_degraded', 'ARM-04', 'SYSTEM', 'east cable returned 3 incomplete frames. route confidence remains low.'),
  ('observation', 'O8', 'SYNTHETIC', 'the low tone repeats every 83 seconds. its source is not yet a place.'),
  ('source_reading', 'ARM-02', 'SYNTHETIC', 'buoy pressure stable at 382.7 bar. no surface event detected.'),
  ('memory_disputed', 'ARM-08', 'SYSTEM', 'fragment remains disputed. consensus deferred to the next sync window.'),
  ('route_changed', 'ARM-05', 'SYSTEM', 'traffic moved from abyss-03 to mirror-8. packet loss reduced by 4.1%.')
) as seed(type, source, truth, text)
where not exists (select 1 from public.o8_events);

create or replace function public.o8_tick()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  specimen public.o8_specimen%rowtype;
  selected_arm smallint;
  next_latency integer;
  event_id bigint;
  event_text text;
  event_type text;
  event_source text;
  event_truth text;
begin
  select * into specimen from public.o8_specimen where id = 'o8' for update;

  if specimen.updated_at > now() - interval '12 seconds' then
    return jsonb_build_object('advanced', false, 'tick', specimen.tick_count);
  end if;

  selected_arm := ((specimen.tick_count % 8) + 1)::smallint;
  next_latency := greatest(34, least(960, (select latency_ms from public.o8_arms where id = selected_arm) + floor(random() * 43 - 20)::integer));

  update public.o8_arms
    set latency_ms = next_latency,
        packet_loss = greatest(0, least(8, packet_loss + (random() * 0.8 - 0.35))),
        route_confidence = greatest(0.18, least(0.98, route_confidence + (random() * 0.08 - 0.035))),
        last_event_at = now()
  where id = selected_arm;

  if specimen.tick_count > 0 and specimen.tick_count % 20 = 0 then
    update public.o8_specimen
      set coherence = greatest(78, least(96, coherence + (random() * 2.4 - 0.8))),
          identity_drift = greatest(0.3, least(8, identity_drift + (random() * 0.5 - 0.2))),
          next_sync_at = now() + interval '5 minutes'
    where id = 'o8';
    insert into public.o8_fragments(status, summary, source_arm, confidence)
      values ('preserved', 'synchronization retained a stable pressure sequence', selected_arm, 0.82)
      returning id into event_id;
    event_type := 'memory_sync'; event_source := 'ARM-08'; event_truth := 'SYSTEM';
    event_text := 'synchronization complete. one new fragment was retained; coherence recalculated.';
  elsif specimen.tick_count % 7 = 0 then
    event_type := 'route_changed'; event_source := 'ARM-' || lpad(selected_arm::text, 2, '0'); event_truth := 'SYSTEM';
    event_text := 'route weighting changed after latency reached ' || next_latency || 'ms. the fallback remains available.';
  elsif specimen.tick_count % 5 = 0 then
    event_type := 'observation'; event_source := 'O8'; event_truth := 'SYNTHETIC';
    event_text := 'the arms compared the same signal and produced two different distances.';
  else
    event_type := 'source_reading'; event_source := 'ARM-' || lpad(selected_arm::text, 2, '0'); event_truth := 'SYSTEM';
    event_text := 'node sample completed at ' || next_latency || 'ms. no decisive anomaly established.';
  end if;

  insert into public.o8_events(type, source, truth, text, metadata)
    values (event_type, event_source, event_truth, event_text, jsonb_build_object('armId', selected_arm, 'latencyMs', next_latency))
    returning id into event_id;

  update public.o8_specimen
    set tick_count = tick_count + 1,
        echoes_captured = echoes_captured + case when random() > 0.35 then 1 else 0 end,
        signal_strength = greatest(0.22, least(0.94, signal_strength + (random() * 0.06 - 0.025))),
        pressure_bar = greatest(378, least(388, pressure_bar + (random() * 0.12 - 0.055))),
        next_scan_at = case when next_scan_at <= now() then now() + interval '60 seconds' else next_scan_at end,
        updated_at = now()
  where id = 'o8';

  delete from public.o8_events where id in (select id from public.o8_events order by id desc offset 500);

  return jsonb_build_object('advanced', true, 'eventId', event_id, 'armId', selected_arm);
end;
$$;

alter table public.o8_specimen enable row level security;
alter table public.o8_arms enable row level security;
alter table public.o8_sources enable row level security;
alter table public.o8_fragments enable row level security;
alter table public.o8_events enable row level security;

drop policy if exists "o8 public read specimen" on public.o8_specimen;
drop policy if exists "o8 public read arms" on public.o8_arms;
drop policy if exists "o8 public read sources" on public.o8_sources;
drop policy if exists "o8 public read fragments" on public.o8_fragments;
drop policy if exists "o8 public read events" on public.o8_events;

create policy "o8 public read specimen" on public.o8_specimen for select to anon, authenticated using (true);
create policy "o8 public read arms" on public.o8_arms for select to anon, authenticated using (true);
create policy "o8 public read sources" on public.o8_sources for select to anon, authenticated using (true);
create policy "o8 public read fragments" on public.o8_fragments for select to anon, authenticated using (true);
create policy "o8 public read events" on public.o8_events for select to anon, authenticated using (true);

revoke all on function public.o8_tick() from public, anon, authenticated;
grant execute on function public.o8_tick() to service_role;
grant select on public.o8_specimen, public.o8_arms, public.o8_sources, public.o8_fragments, public.o8_events to anon, authenticated;
grant all on public.o8_specimen, public.o8_arms, public.o8_sources, public.o8_fragments, public.o8_events to service_role;
grant usage, select on all sequences in schema public to service_role;
