import { allowMethod, supabaseRequest } from "../../lib/supabase-server.js";

export default async function handler(request, response) {
  if (!allowMethod(request, response, ["GET"])) return;
  try {
    const [specimens, arms, sources, bindings, tokenTargets, lifecycleSnapshots, lifecycleEvents, dissentRecords, storyMilestones, storyStates, targetSnapshots, chainBlocks, hiveCells, microMilestones, foragerIdentities, memoryProposals] = await Promise.all([
      supabaseRequest("/o8_specimen?id=eq.o8&select=*"),
      supabaseRequest("/o8_arms?select=*&order=id.asc"),
      supabaseRequest("/o8_sources?select=*&order=id.asc"),
      supabaseRequest("/o8_system_bindings?select=*&order=id.asc"),
      supabaseRequest("/o8_token_targets?id=eq.o8&select=*"),
      supabaseRequest("/o8_token_lifecycle_snapshots?target_id=eq.o8&select=*&order=id.desc&limit=8"),
      supabaseRequest("/o8_lifecycle_events?select=*&order=occurred_at.desc&limit=8"),
      supabaseRequest("/o8_dissent_records?select=*&order=occurred_at.desc&limit=4"),
      supabaseRequest("/o8_story_milestones?select=*&order=occurred_at.desc&limit=24"),
      supabaseRequest("/o8_story_state?select=*&order=updated_at.desc&limit=2"),
      supabaseRequest("/o8_target_block_snapshots?select=target_address,block_number,target_status,metrics,observed_at&order=block_number.desc&limit=32"),
      supabaseRequest("/o8_chain_blocks?select=block_number,transaction_count,block_timestamp&order=block_number.desc&limit=24"),
      supabaseRequest("/o8_hive_cells?select=*&order=created_at.desc&limit=64"),
      supabaseRequest("/o8_micro_milestones?select=*&order=occurred_at.desc&limit=64"),
      supabaseRequest("/o8_forager_identities?select=*&order=updated_at.desc&limit=64"),
      supabaseRequest("/o8_memory_proposals?select=id,target_address,proposer_address,title,question,status,evidence,created_at,reviewed_at&order=created_at.desc&limit=32"),
    ]);
    const specimen = specimens[0];
    response.setHeader("Cache-Control", "no-store");
    response.status(200).json({
      serverTime: new Date().toISOString(),
      specimen: {
        id: specimen.id,
        status: specimen.status,
        observerHeartbeats: specimen.tick_count,
        updatedAt: specimen.updated_at,
      },
      arms: arms.map((arm) => ({
        id: arm.id,
        agentName: arm.agent_name,
        role: arm.role,
        domain: arm.domain,
        temperament: arm.temperament,
        mood: arm.mood,
        moodReason: arm.mood_reason,
        voice: arm.voice,
        state: arm.state,
        nodeName: arm.node_name,
        latencyMs: arm.latency_ms,
        packetLoss: Number(arm.packet_loss),
        routeConfidence: Number(arm.route_confidence),
      })),
      sources: sources.map((source) => ({
        id: source.id,
        label: source.label,
        kind: source.kind,
        truth: source.truth,
        status: source.status,
        latencyMs: source.latency_ms,
        lastCheckedAt: source.last_checked_at,
        payload: source.payload,
      })),
      bindings: bindings.map((binding) => binding.id === "minimax" ? {
        id: "agent-voices",
        label: "COMB Agent Voices",
        status: binding.details?.providerConfigured ? "READY" : "DORMANT",
        truth: binding.truth,
        details: {
          ready: Boolean(binding.details?.providerConfigured),
          agents: ["WATCHER", "CURRENT", "DEPTH", "CHORUS", "AUDITOR", "HUNTER", "KEEPER", "ARCHIVE"],
        },
        updatedAt: binding.updated_at,
      } : {
        id: binding.id,
        label: binding.label,
        status: binding.status,
        truth: binding.truth,
        details: binding.details,
        updatedAt: binding.updated_at,
      }),
      token: tokenTargets[0] ? {
        id: tokenTargets[0].id,
        platform: tokenTargets[0].platform,
        status: tokenTargets[0].status,
        name: tokenTargets[0].token_name === "$O8" ? "$COMB" : tokenTargets[0].token_name,
        symbol: !tokenTargets[0].symbol || tokenTargets[0].symbol === "O8" ? "COMB" : tokenTargets[0].symbol,
        tokenAddress: tokenTargets[0].token_address,
        deployerAddress: tokenTargets[0].deployer_address,
        poolAddress: tokenTargets[0].pool_address,
        pairTokenAddress: tokenTargets[0].pair_token_address,
        launchTxHash: tokenTargets[0].launch_tx_hash,
        launchBlock: tokenTargets[0].launch_block,
        launchedAt: tokenTargets[0].launched_at,
        graduationProgressPct: tokenTargets[0].graduation_progress === null ? null : Number(tokenTargets[0].graduation_progress),
        pairedPrincipalWei: tokenTargets[0].paired_principal_wei,
        graduationThresholdWei: tokenTargets[0].graduation_threshold_wei,
        graduated: tokenTargets[0].graduated,
        priceUsd: tokenTargets[0].price_usd === null ? null : Number(tokenTargets[0].price_usd),
        marketCapUsd: tokenTargets[0].market_cap_usd === null ? null : Number(tokenTargets[0].market_cap_usd),
        metadata: tokenTargets[0].metadata,
        updatedAt: tokenTargets[0].updated_at,
      } : null,
      tokenLifecycle: lifecycleSnapshots.map((item) => ({
        id: item.id,
        observedAt: item.observed_at,
        status: item.status,
        graduationProgressPct: item.graduation_progress === null ? null : Number(item.graduation_progress),
        pairedPrincipalWei: item.paired_principal_wei,
        graduationThresholdWei: item.graduation_threshold_wei,
        poolAddress: item.pool_address,
        poolLiquidity: item.pool_liquidity,
        observedBlock: item.observed_block,
      })),
      lifecycleEvents: lifecycleEvents.map((item) => ({
        id: item.id,
        targetAddress: item.target_address,
        phaseCode: item.phase_code,
        phaseName: item.phase_name,
        title: item.title,
        description: item.description,
        truth: item.truth,
        observedBlock: item.observed_block,
        evidence: item.evidence,
        ceremony: item.ceremony,
        occurredAt: item.occurred_at,
      })),
      dissentRecords: dissentRecords.map((item) => ({
        id: item.id,
        targetAddress: item.target_address,
        phaseCode: item.phase_code,
        lifecycleEventId: item.lifecycle_event_id,
        truth: item.truth,
        summary: item.summary,
        positions: item.positions,
        evidence: item.evidence,
        occurredAt: item.occurred_at,
      })),
      storyMilestones: storyMilestones.map((item) => ({
        id: item.id,
        targetAddress: item.target_address,
        eventKey: item.event_key,
        category: item.category,
        eventType: item.event_type,
        title: item.title,
        description: item.description,
        truth: item.truth,
        source: item.source,
        observedBlock: item.observed_block,
        evidence: item.evidence,
        occurredAt: item.occurred_at,
      })),
      hiveCells: hiveCells.map((item) => ({
        id: item.id,
        cellKey: item.cell_key,
        cellType: item.cell_type,
        status: item.status,
        title: item.title,
        description: item.description,
        truth: item.truth,
        sourceEventId: item.source_event_id,
        targetAddress: item.target_address,
        observedBlock: item.observed_block,
        evidence: item.evidence,
        createdAt: item.created_at,
      })),
      microMilestones: microMilestones.map((item) => ({
        id: item.id,
        targetAddress: item.target_address,
        milestoneKey: item.milestone_key,
        milestoneType: item.milestone_type,
        title: item.title,
        description: item.description,
        truth: item.truth,
        observedBlock: item.observed_block,
        evidence: item.evidence,
        occurredAt: item.occurred_at,
      })),
      foragerIdentities: foragerIdentities.map((item) => ({
        id: item.id,
        targetAddress: item.target_address,
        walletAddress: item.wallet_address,
        identityType: item.identity_type,
        label: item.label,
        firstSeenBlock: item.first_seen_block,
        lastSeenBlock: item.last_seen_block,
        evidence: item.evidence,
        updatedAt: item.updated_at,
      })),
      memoryProposals: memoryProposals.map((item) => ({
        id: item.id,
        targetAddress: item.target_address,
        proposerAddress: item.proposer_address,
        title: item.title,
        question: item.question,
        status: item.status,
        evidence: item.evidence,
        createdAt: item.created_at,
        reviewedAt: item.reviewed_at,
      })),
      storyState: storyStates[0] ? {
        targetAddress: storyStates[0].target_address,
        highProgressPct: Number(storyStates[0].high_progress),
        lastProgressPct: storyStates[0].last_progress === null ? null : Number(storyStates[0].last_progress),
        lastProgressAt: storyStates[0].last_progress_at,
        lastActivityAt: storyStates[0].last_activity_at,
        lastActivityBlock: storyStates[0].last_activity_block,
        observerHealth: storyStates[0].observer_health,
        silenceState: storyStates[0].silence_state,
        graduatedBlock: storyStates[0].graduated_block,
        baseline: storyStates[0].baseline,
        baselineSampleCount: storyStates[0].baseline_sample_count,
        baselineReadyAt: storyStates[0].baseline_ready_at,
        updatedAt: storyStates[0].updated_at,
      } : null,
      targetTrace: targetSnapshots.map((item) => ({
        targetAddress: item.target_address,
        blockNumber: item.block_number,
        targetStatus: item.target_status,
        transactionCount: Number(item.metrics?.transactionCount || 0),
        tokenTransferCount: Number(item.metrics?.tokenTransferCount || 0),
        poolEventCount: Number(item.metrics?.poolEventCount || 0),
        observedAt: item.observed_at,
      })),
      networkTrace: chainBlocks.map((item) => ({
        blockNumber: item.block_number,
        transactionCount: Number(item.transaction_count || 0),
        observedAt: item.block_timestamp,
      })),
    });
  } catch (error) {
    response.status(503).json({ error: "specimen state unavailable", detail: error.message });
  }
}
